<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zyneonstudios</groupId>
        <artifactId>application-parent</artifactId>
        <version>1.6.0</version>
    </parent>

    <artifactId>application-main</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <app.mainClass>com.zyneonstudios.ApplicationMain</app.mainClass>
        <app.name>NEX App (Old, Zyneon Application)</app.name>
        <app.vendor>Zyneon Apex</app.vendor>
        <app.version.jpackage>${version}</app.version.jpackage>
    </properties>

    <repositories>
        <repository>
            <id>nerofy-releases</id>
            <name>Repository-r</name>
            <url>https://maven.nrfy.net/releases</url>
        </repository>
        <repository>
            <id>nerofy-snapshots</id>
            <name>Repository-s</name>
            <url>https://maven.nrfy.net/snapshots</url>
        </repository>
        <repository>
            <id>nerofy-pivate</id>
            <name>Repository-p</name>
            <url>https://maven.nrfy.net/private</url>
        </repository>
    </repositories>

    <dependencies>
        <!--Dependencies by Zyneon Apex Team-->
        <dependency>
            <groupId>com.zyneonstudios.nexus</groupId>
            <artifactId>zyndex-java</artifactId>
            <version>2025.5.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.zyneonstudios.nexus</groupId>
            <artifactId>mojang-auth</artifactId>
            <version>2024.8.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.zyneonstudios.nexus</groupId>
            <artifactId>verget-all</artifactId>
            <version>2024.8.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.zyneonstudios.nexus</groupId>
            <artifactId>base-desktop</artifactId>
            <version>2025.5.4</version>
            <scope>compile</scope>
        </dependency>

        <!--Dependencies by FlowArg-->
        <dependency>
            <groupId>fr.flowarg</groupId>
            <artifactId>flowupdater</artifactId>
            <version>1.9.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>fr.flowarg</groupId>
            <artifactId>openlauncherlib</artifactId>
            <version>3.2.11</version>
            <scope>compile</scope>
        </dependency>

        <!--Something... that is used?.... in the code?-->
        <dependency>
            <groupId>com.moandjiezana.toml</groupId>
            <artifactId>toml4j</artifactId>
            <version>LATEST</version>
        </dependency>

        <!--Fix vulnerabilities from dependencies with newer versions of their dependencies-->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>LATEST</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.zyneonstudios.ApplicationMain</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${app.mainClass}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>jdeb</artifactId>
                <groupId>org.vafer</groupId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>jdeb</goal>
                        </goals>
                        <configuration>
                            <dataSet>
                                <data>
                                    <src>src/deb/nex-app.jar</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <filemode>755</filemode>
                                        <prefix>/usr/bin/zyneon/application/</prefix>
                                    </mapper>
                                </data>
                                <data>
                                    <src>src/deb/icon.png</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/usr/bin/zyneon/application/</prefix>
                                    </mapper>
                                </data>
                                <data>
                                    <src>src/deb/nexus-app.desktop</src>
                                    <type>file</type>
                                    <mapper>
                                        <type>perm</type>
                                        <filemode>755</filemode>
                                        <prefix>/usr/share/applications/</prefix>
                                    </mapper>
                                </data>
                            </dataSet>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>eot</nonFilteredFileExtension>
                        <nonFilteredFileExtension>ttf</nonFilteredFileExtension>
                        <nonFilteredFileExtension>woff</nonFilteredFileExtension>
                        <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
                        <nonFilteredFileExtension>zip</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>windows-exe</id>
            <activation>
                <os>
                    <family>Windows</family>
                </os>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-antrun-plugin</artifactId>
                        <version>3.2.0</version>
                        <executions>
                            <execution>
                                <id>remove-read-only-for-clean</id>
                                <phase>pre-clean</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <exec executable="cmd" failonerror="false">
                                            <arg value="/c"/>
                                            <arg value="attrib"/>
                                            <arg value="-R"/>
                                            <arg value="${project.build.directory}\*.*"/>
                                            <arg value="/S"/>
                                            <arg value="/D"/>
                                        </exec>
                                    </target>
                                </configuration>
                            </execution>
                            <execution>
                                <id>remove-read-only-for-appimage</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <exec executable="cmd" failonerror="true">
                                            <arg value="/c"/>
                                            <arg value="attrib"/>
                                            <arg value="-R"/>
                                            <arg value="${project.build.directory}\jpackage\${app.name}\*.*"/>
                                            <arg value="/S"/>
                                            <arg value="/D"/>
                                        </exec>
                                    </target>
                                </configuration>
                            </execution>
                            <execution>
                                <id>remove-read-only-for-installers</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                                <configuration>
                                    <target>
                                        <exec executable="cmd" failonerror="true">
                                            <arg value="/c"/>
                                            <arg value="attrib"/>
                                            <arg value="-R"/>
                                            <arg value="${project.build.directory}\jpackage\*.*"/>
                                        </exec>
                                    </target>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.7.4</version>
                        <executions>
                            <execution>
                                <id>jpackage</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <input>${project.build.directory}</input>
                                    <destination>${project.build.directory}/jpackage</destination>
                                    <name>${app.name}</name>
                                    <appVersion>${app.version.jpackage}</appVersion>
                                    <vendor>${app.vendor}</vendor>
                                    <mainJar>${project.build.finalName}.jar</mainJar>
                                    <mainClass>${app.mainClass}</mainClass>
                                    <icon>${project.basedir}/src/main/resources/favicon.ico</icon>
                                    <type>APP_IMAGE</type>
                                </configuration>
                            </execution>
                            <execution>
                                <id>jpackage-installer</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <appImage>${project.build.directory}/jpackage/${app.name}</appImage>
                                    <destination>${project.build.directory}/jpackage</destination>
                                    <name>${app.name}</name>
                                    <appVersion>${app.version.jpackage}</appVersion>
                                    <vendor>${app.vendor}</vendor>
                                    <icon>${project.basedir}/src/main/resources/favicon.ico</icon>
                                    <type>EXE</type>
                                    <winDirChooser>true</winDirChooser>
                                    <winShortcut>true</winShortcut>
                                    <winMenu>true</winMenu>
                                    <winMenuGroup>${app.vendor}</winMenuGroup>
                                </configuration>
                            </execution>
                            <execution>
                                <id>jpackage-installer-msi</id>
                                <phase>integration-test</phase>
                                <goals>
                                    <goal>jpackage</goal>
                                </goals>
                                <configuration>
                                    <appImage>${project.build.directory}/jpackage/${app.name}</appImage>
                                    <destination>${project.build.directory}/jpackage</destination>
                                    <name>${app.name}</name>
                                    <appVersion>${app.version.jpackage}</appVersion>
                                    <vendor>${app.vendor}</vendor>
                                    <icon>${project.basedir}/src/main/resources/favicon.ico</icon>
                                    <type>MSI</type>
                                    <winDirChooser>true</winDirChooser>
                                    <winShortcut>true</winShortcut>
                                    <winMenu>true</winMenu>
                                    <winMenuGroup>${app.vendor}</winMenuGroup>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>net.jsign</groupId>
                        <artifactId>jsign-maven-plugin</artifactId>
                        <version>7.5</version>
                        <executions>
                            <execution>
                                <id>sign-app-image</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <file>${project.build.directory}/jpackage/${app.name}/${app.name}.exe</file>
                                    <keystore>${project.basedir}/cert.pfx</keystore>
                                    <storepass>${sign.cert.password}</storepass>
                                    <tsaurl>http://timestamp.digicert.com</tsaurl>
                                </configuration>
                            </execution>

                            <execution>
                                <id>sign-installer</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <file>${project.build.directory}/jpackage/${app.name}-${app.version.jpackage}.exe</file>
                                    <keystore>${project.basedir}/cert.pfx</keystore>
                                    <storepass>${sign.cert.password}</storepass>
                                    <tsaurl>http://timestamp.digicert.com</tsaurl>
                                </configuration>
                            </execution>

                            <execution>
                                <id>sign-installer-msi</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                                <configuration>
                                    <file>${project.build.directory}/jpackage/${app.name}-${app.version.jpackage}.msi</file>
                                    <keystore>${project.basedir}/cert.pfx</keystore>
                                    <storepass>${sign.cert.password}</storepass>
                                    <tsaurl>http://timestamp.digicert.com</tsaurl>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>